### ISSUE TITLE
Need proper documentation for Popmeta

### ISSUE THREAD

**Issue by sjmack** [alexlancaster/pypop#13]
Currently, in the PyPop docs, Popmeta is undocumented (as of PyPop vs 0.5.1). Some true documentation for Popmeta would be a useful addition to the PyPop docs (or possibly a separate document). I can contribute to the popmeta docs.

**Comment by alexlancaster** [comment]
To help on-going updating of docs, I propose converting to github-flavoured markdown on the wiki here: #34

**Comment by alexlancaster** [comment]
Documentation has been converted to `.rst` (restructured text) for simpler editing. The source is now located in the `website` directory (and subdirectory `docs`). See https://github.com/alexlancaster/pypop/tree/main/website#readme for how to edit/contribute.

**Comment by alexlancaster** [comment]
@sjmack In PR #71 I have made a start on partially addressed this (could probably do with some additional details). You can see the beta version of the docs at https://alexlancaster.github.io/beta.pypop.org/docs/guide-chapter-usage.html#using-popmeta-to-aggregate-results

**Comment by rsingle** [comment]
This looks good
