### ISSUE TITLE
update the links in docs on allele names

### ISSUE THREAD

**Issue by alexlancaster** [alexlancaster/pypop#137]
There's a section in the docs about the different allele names used for creating the `CustomBinning` rules:

>  The Anthony Nolan list of deleted allele names (http://www.anthonynolan.com/HIG/lists/delnames.html); and the Ambiguous Allele Combinations, release 2.18.0 (http://www.ebi.ac.uk/imgt/hla/ambig.html).

(see http://pypop.org/docs/guide-chapter-usage.html#id8)

but all the links are 404.  @rsingle can you supply the updated versions / new links for these references?

**Comment by rsingle** [comment]
Yes. We should probably download new versions of the files too.

**Comment by alexlancaster** [comment]
> Yes. We should probably download new versions of the files too.

agree.  but I wonder in the meantime, if we could at least provide some updated links?  I don't want the 1.0.0 release to be contingent on getting every last thing updated, since we can make new minor releases to fix them (e.g. in 1.0.1 or later).

**Comment by alexlancaster** [comment]
@rsingle Also I noticed that we say just above the links:

> PyPop is distributed with a biologically relevant set of CustomBinning rules that have been compiled from several sources

But  the only place I can find in the repo where we compile a comprehensive list of such rules is in this file, is this what is meant?

https://github.com/alexlancaster/pypop/blob/65788c6d1f37708be768a92d6509b8425c82c4f2/website/html_root/popdata/2008/config-allelecount.ini#L82-L213
