### ISSUE TITLE
MacOS arm64 installation issue

### ISSUE THREAD

**Issue by odoublewen** [alexlancaster/pypop#138]
**Describe the bug**
I could not `pip install pypop-genomics` using python 3.10 on an M1 mac.  The error message was:
```
  swigging src/emhaplofreq/emhaplofreq_wrap.i to src/emhaplofreq/emhaplofreq_wrap_wrap.c
  swig -python -Isrc/SWIG -Isrc -o src/emhaplofreq/emhaplofreq_wrap_wrap.c src/emhaplofreq/emhaplofreq_wrap.i
  error: command 'swig' failed: No such file or directory
```

It's unclear to me whether "no such file" refers to `swig` itself or to one of the files/dirs in the swig args.

Full output is attached:  [pypop-error.txt](https://github.com/alexlancaster/pypop/files/12874736/pypop-error.txt)

**Desktop (please complete the following information):**
 - OS: macOS 12.6.7
 - Python: 3.10.11

**Comment by alexlancaster** [comment]
@odoublewen try and rerun the installation again. Might be useful to post the output of `pip install -vv python-genomics` again.

**Comment by odoublewen** [comment]
Great, it now installs correctly on my M1 mac.  Thanks.
