### ISSUE TITLE
Problem with Linkage Disequilibrium and Wn calculations

### ISSUE THREAD

**Issue by nabil161289** [alexlancaster/pypop#151]
**The values of global LD (D`) and Wn are exceeding 1**
The values of both metrics should fall between 0 and 1

**To Reproduce:**
1. Install PyPOP via cmd: pip install pypop-genomics
2. Download the minimal.ini and the USAFEL-UchiTelle-small.pop (available from https://github.com/alexlancaster/pypop#examples)
3. From cmd, browse to files location, then execute: pypop -c  tests/data/minimal.ini tests/data/USAFEL-UchiTelle-small.pop
4. Examine the USAFEL-UchiTelle-small-out.txt

**Expected behavior**
At the "Pairwise LD estimates" section, values of D' and Wn should be between 0 and 1, yet, D' values significantly exceed 1 and Wn exceed 2.

**Screenshots**
![image](https://github.com/alexlancaster/pypop/assets/149200830/259d2402-da7c-4f9b-a2ef-4a4ac86d961e)

**Desktop:**
 - Device: HP EliteBook 840 G2 Notebook PC
 - OS: Windows 10 pro (Version 22H2)
 - Python version: 3.11
 - PIP version: 23.2.1
 - PyPOP version: 1.0.0b4

[Example.zip](https://github.com/alexlancaster/pypop/files/13192694/Example.zip)

**Comment by nabil161289** [comment]
@alexlancaster

**Comment by alexlancaster** [comment]
hi @nabil161289 thanks for the report - we have fixed a bug recently that looks somewhat similar to yours (#147), can you try and test this new pre-release `1.0.0b7`, and re-run the example? you should be able to update via `pip`:

```
pip install -U pypop-genomics
```

**Comment by nabil161289** [comment]
Dear Prof. Alex,
Thank you so much sir, I updated PyPOP to the new-pre-release and the
values are within range.
However, I would like to point out another problem:
I was trying to estimate the LD using "pould" in R. The values after the
fix are similar to the Unphased LD, not a Phased LD.
Please take a look:
PyPOP (after updating):
[image: image.png]
pould, unphased LD:
Loc1~Loc2 D' Wn WLoc1/Loc2 WLoc2/Loc1 N_Haplotypes
C~A 0.885302198 0.770229815 0.7617394 0.753370804 14
C~B 1 Inf Inf 0 9
A~B 0 NaN NaN 0 8

pould, Phased LD

Loc1~Loc2 D' Wn WLoc1/Loc2 WLoc2/Loc1 N_Haplotypes
C~A 0.803342491 0.712696645 0.693888666 0.650709938 16
C~B 1 Inf Inf 0 9
A~B 0 NaN NaN 0 8

pould compares phased to unphased LD via a sign test.
The R code:
[image: image.png]
Can you please confirm whether the LD calculated by PyPOP is unphased or
phasedLD?
And again, thanks for everything and for disturbing you.
Much obliged,
Nabil

**Comment by alexlancaster** [comment]
> Dear Prof. Alex, Thank you so much sir, I updated PyPOP to the new-pre-release and the values are within range. However, I would like to point out another problem: I was trying to estimate the LD using "pould" in R. The values after the fix are similar to the Unphased LD, not a Phased LD. 

Hi @nabil161289 good to know that it fixed your original report.   I will close this issue.

For the second issue, could you please open up a  new _separate_ bug for that issue and supply the same information so we can reproduce it?

In addition :

1. when you reply by email, you can't add images.  You'll need to visit the github issue on the website to upload images. 
2.  It's also better if you can use the github markdown for code input so it's easier to read, e.g.

\`\`\`
this is code
\`\`\`

produces the following:

```
this is code
```

this is also easier to add when you add comments to the issue directly on github.

**Comment by alexlancaster** [comment]
fixed by #150

**Comment by rsingle** [comment]
Hi Nabil,
PyPop is set to work with unphased data, so it will only agree with the unphased computations from POULD.
Best,
Rich

Richard Single, Ph.D.
Graduate Program Director in Statistics
University of Vermont
