### ISSUE TITLE
[Documentation]: Links to .ini and .pop exemplars are reversed

### ISSUE THREAD

**Issue by sjmack** [alexlancaster/pypop#203]
### Is your issue related to the main website?

No

### Is your issue related to documentation?

Yes

### Is your issue related to other parts of the documentation?

No

### Is your documentation issue...?

both reporting an error and a making a proposed improvement

### Describe documentation issue

The links to the .ini and .pop exemplars in Section 2.1 of the [PyPop instructions page](http://pypop.org/docs/guide-chapter-usage.html) are "reversed". 

The configuration file link takes you to an example of a .pop file, and the population file link takes you to an example of a .ini file.

I propose that the links be corrected.

**Comment by alexlancaster** [comment]
@sjmack : should be fixed now on http://pypop.org/docs/guide-chapter-usage.html

**Comment by sjmack** [comment]
Looks good. Thanks.
