### ISSUE TITLE
increase the number of individuals and loci that emhaplofreq can process

### ISSUE THREAD

**Issue by alexlancaster** [alexlancaster/pypop#26]
@sjmack, in the haplo.stats branch, I've increased the number the individuals to 100k and 20 loci that ```emhaplofreq``` can accept.  I have processed a data file that consisted of your 5000 line synthetic data set repeated 20 times.  To test:

     git checkout haplo-stats
     ./setup.py build

You need one more Python package ```psutils``` for testing, details here: https://github.com/alexlancaster/pypop/tree/haplo-stats#running-test-suite

Then run the test on it's own:

     py.test -s -v tests/test_100k_Emhaplofreq.py

You'll need to make sure you have at least 6-8 GB free of memory.  I'm not exactly sure how much memory is really required, but you'll probably want as much as you can.

This will estimate the haplotype frequencies for just a single pair of loci.  Without knowing how representative of workshop data the synthetic data is, it's difficult to know how well this will work in general, but it provides a potential fallback.

**Comment by sjmack** [comment]
No Joy. 

```
:pypop sjmack$ py.test -s -v tests/test_100k_Emhaplofreq.py
================================================================= test session starts ==================================================================
platform darwin -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0 -- /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
cachedir: .cache
rootdir: /Applications/PyPop/pypop, inifile:
collected 1 items 

tests/test_100k_Emhaplofreq.py::test_100k_Emhaplofreq FAILED

======================================================================= FAILURES =======================================================================
________________________________________________________________ test_100k_Emhaplofreq _________________________________________________________________

    @pytest.mark.skipif(psutil.virtual_memory().available <= memory_in_bytes, reason="test can only be run if there is sufficient memory on the machine")
    def test_100k_Emhaplofreq():
        process=subprocess.Popen(
    	['./bin/pypop.py', '-m', '-c', './tests/data/Test_100k_20loci_Dataset.ini', './tests/data/Test_100k_20loci_Dataset.pop'],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT
            )
        process.communicate()
        exit_code = process.wait()  # wait until script completed
    
        # check exit code
        assert exit_code == 0
        # compare with md5sum of output file
>       assert hashlib.md5(open("Test_100k_20loci_Dataset-out.txt", 'rb').read()).hexdigest() == 'd899396e90d99ad9eb2002506e699091'
E       AssertionError: assert '34765dde2f50...11f8e893be4f0' == 'd899396e90d99...002506e699091'
E         - 34765dde2f5068cc02811f8e893be4f0
E         + d899396e90d99ad9eb2002506e699091

tests/test_100k_Emhaplofreq.py:23: AssertionError
============================================================== 1 failed in 948.54 seconds ==============================================================

```

**Comment by sjmack** [comment]
Oh, I should add that I had 8GB of RAM free. 

```
MacBook Pro (15-inch, 2017
Processor 3.1 GHz Intel Core i7
Memory 16 GB 2133 MHz LPDDR3

```

**Comment by alexlancaster** [comment]
Ah, but it ran to completion. That's the main thing.  The assert failure is on the file comparison, that's probably easily fixed. Can you upload the txt and XML outputs?

**Comment by sjmack** [comment]
I see. Here are the files -- looks like the emhaplofreq may need some parameter tweaking to work with such large datasets.

I just tested the estimation of haoplotypes using the haplo.stats haplo.em function (in [BIGDAWG](https://github.com/IgDAWG/BIGDAWG/)) for locus A and B, and got haplotypes in seconds with no problem. So there's something off here. 

[Test_100k_20loci_Dataset-out.txt](https://github.com/alexlancaster/pypop/files/1157965/Test_100k_20loci_Dataset-out.txt)
[Test_100k_20loci_Dataset-out.xml.txt](https://github.com/alexlancaster/pypop/files/1157966/Test_100k_20loci_Dataset-out.xml.txt)

**Comment by alexlancaster** [comment]
The second assert failure was most likely that I hadn't updated the checksum since we made all the other unrelated changes.  I might remove that for the moment.

Yes, this is a fallback option. We're working on getting haplo.stats integrated and making progress, but it's a nontrivial job.  As to why it's taking so much longer, Rich might have an answer on that one.

**Comment by alexlancaster** [comment]
Yes, it looks like the haplotype estimates do not converge, whether I run it on Linux or Mac.  Initially I thought this might be a platform-dependent / numerical issue.

**Comment by sjmack** [comment]
It might be illustrative to figure out what the largest N is under which you can get convergence.

**Comment by alexlancaster** [comment]
Good idea, I might try that, but my overall gut feeling is that spending too much more time on emhaplofreq is going to have diminishing returns. Getting haplo.stats online is probably going to be more fruitful at this point.

**Comment by sjmack** [comment]
I agree. Using haplo.stats will open currently unavailable avenues -- like using returning specific haplotypes for each subject, using posterior probabilities.

**Comment by rsingle** [comment]
I agree, and so far so good ...

=======================================
Richard M. Single, Ph.D.
Dept. of Mathematics and Statistics
University of Vermont
306 Mansfield House
Burlington, VT 05405
802-656-8631, Richard.Single@uvm.edu
=======================================

**Comment by alexlancaster** [comment]
OK, I opened up #28 on haplo.stats so there's a ticket. I'm going to mark this as "Nice-To-Have" and make #28 "High" since there seems to be agreement on prioritizing the haplo.stats implementation.

**Comment by alexlancaster** [comment]
Based on feedback from testers and other indications, looks like spending more time on improving emhaplofreq has reached the end of the road, so I'll close this bug for now.
