### ISSUE TITLE
Modify PopMeta parameters so that IHWG headers have to be opted-in

### ISSUE THREAD

**Issue by sjmack** [alexlancaster/pypop#27]
Currently, popmeta.py defaults to expect IHWG header block data in the out.xml files. In order to generate compact TSV files without numerous extra fields, one must supply the --disable-ihwg argument. 

A this point, it seems unlikely that many users are using the specific IHWG headers, so it would probably be useful to change the --disable-ihwg argument to --enable-ihwg, so that the default is no expectation of header data. 

This would also make it possible to run pypop with the --generate-tsv argument, and generate compact TSV files, without having to use popmeta separately.

**Comment by alexlancaster** [comment]
@sjmack: would you say this is "High" or "Nice-To-Have" for the moment?

**Comment by sjmack** [comment]
I guess it depends on how much work it would be to implement, if it is a simple fix -- changing a some TRUEs to FALSEs -- then it would be "High", if it involves a lot of coding then it would be nice to have.

Basically, we'll have to do analyses in two steps without the change, or one step with. If this fix is easier than scripting two lines:
```
pypop.py -c *.ini *.pop
popmeta.py --disable-ihwg *-out.xml
```

Instead of scripting `pypop.py --generate-tsv -c *.ini *.pop`

Then mark it High.

**Comment by alexlancaster** [comment]
It's hard to say how much work it will be without looking at it in detail, which is why we need a priority. :)  I'm going to mark it as Nice-To-Have for the moment, since there's a workaround.

**Comment by alexlancaster** [comment]
I switched the login for `popmeta` in the https://github.com/alexlancaster/pypop/tree/tsv_files branch, so there is now a `--enable-ihwg` option, rather than `--disable-ihwg`.  There's a bit more work to make this the default for `pypop` itself.
