### ISSUE TITLE
Empty popmeta TSV files are being generated for analyses not called for in the config file

### ISSUE THREAD

**Issue by sjmack** [alexlancaster/pypop#29]
`./bin/pypop.py --generate-tsv -c WS_BDCtrl_Test_HW_lite.ini BIGDAWG_SynthControl_Data.pop`

Generates the following .TSV files:
```
1-locus-allele.dat		1-locus-pairwise-fnd.dat	2-locus-summary.dat		4-locus-haplo.dat
1-locus-genotype.dat		1-locus-summary.dat		3-locus-haplo.dat		4-locus-summary.dat
1-locus-hardyweinberg.dat	2-locus-haplo.dat		3-locus-summary.dat
```
Even though WS_BDCtrl_Test_HW_lite.ini is calling for HW tests at a single locus: 

```
;; comment out or change as desired
;; 1 = true, 0 = false

[General]
debug=0

[ParseGenotypeFile]
untypedAllele=****

;; designates field name that holds population name
popNameDesignator=+

;; designates field name that holds allele data
alleleDesignator=*

;; valid fields for sample data block
validSampleFields=SampleID
 +Disease
 *A_1
 *A_2
; *B_1
; *B_2
; *C_1
; *C_2
; *DPA1_1
; *DPA1_2
; *DPB1_1
; *DPB1_2
; *DQA1_1
; *DQA1_2
; *DQB1_1
; *DQB1_2
; *DRB1_1
; *DRB1_2
; *DRB3_1
; *DRB3_2
; *DRB4_1
; *DRB4_2
; *DRB5_1
; *DRB5_2
; *HLA-A_1
; *HLA-A_2
; *HLA-B_1
; *HLA-B_2
; *HLA-C_1
; *HLA-C_2
; *HLA-DPA1_1
; *HLA-DPA1_2
; *HLA-DPB1_1
; *HLA-DPB1_2
; *HLA-DQA1_1
; *HLA-DQA1_2
; *HLA-DQB1_1
; *HLA-DQB1_2
; *HLA-DRB1_1
; *HLA-DRB1_2
; *HLA-DRB3_1
; *HLA-DRB3_2


[HardyWeinberg]
lumpBelow=5

[HardyWeinbergGuoThompsonMonteCarlo]
monteCarloSteps=100000
```

Of the files generated, only 1-locus-allele.dat, 1-locus-summary.dat, 1-locus-genotype.dat and 1-locus-hardyweinberg.dat should be generated. The rest contain only headers. 

```
:pypop sjmack$ more 1-locus-pairwise-fnd.dat 
pop     labcode method  ethnic  collect.site    region  latit   longit  complex locus1  locus2  metaloci        f.slatkin.fnd
:pypop sjmack$ more 2-locus-haplo.dat 
pop     labcode method  ethnic  collect.site    region  latit   longit  complex locus   allele  allele.freq     allele.count    ld.d    ld.dprime       ld.chisq        obs     obs.freq        exp
:pypop sjmack$ more 2-locus-summary.dat 
pop     labcode method  ethnic  collect.site    region  latit   longit  complex n.gametes       locus1  locus2  metaloci        ld.dprime       ld.wn   q.chisq q.df    lrt.pval        lrt.z
:pypop sjmack$ more 3-locus-haplo.dat
pop     labcode method  ethnic  collect.site    region  latit   longit  complex locus   allele  allele.freq     allele.count
:pypop sjmack$ more 3-locus-summary.dat
n.gametes       locus1  locus2  locus3
:pypop sjmack$ more 4-locus-haplo.dat 
pop     labcode method  ethnic  collect.site    region  latit   longit  complex locus   allele  allele.freq     allele.count
:pypop sjmack$ more 4-locus-summary.dat 
pop     labcode method  ethnic  collect.site    region  latit   longit  complex n.gametes       locus1  locus2  locus3  locus4
:pypop sjmack$
```

The other files shouldn't be generated unless the appropriate analyses are calling them.

**Comment by sjmack** [comment]
Further, *only* these hard-coded TSV files are being generated. iIf e.g., five- or six-locus haplotype analyses are specified in the .ini, popmeta does not generate 5-locus-haplo.dat or 6-lcous-summary.dat files.

Future verslons of popmeta should decide what TSV files to generate based on the specific results in the pertinent *out.xml file.

**Comment by alexlancaster** [comment]
> Further, _only_ these hard-coded TSV files are being generated. If e.g., five- or six-locus haplotype analyses are specified in the .ini, popmeta does not generate 5-locus-haplo.dat or 6-lcous-summary.dat files.
> 
> Future verslons of popmeta should decide what TSV files to generate based on the specific results in the pertinent *out.xml file.

Agree - this would be the ideal behaviour.  However, generating the file names based on the number of loci called, rather than hardcoding files for the 2,3,4 loci haplotype cases would require a fairly non-trivial amount of work with the current way that the XML generates the `.dat` files.  Since generation of additional files is not an error per se, reclassifying this as an enhancement rather than a bug.  The generation of the dat files was optimized for the needs of the 13th workshop.
