### ISSUE TITLE
make HW work with colon-delimited allele names

### ISSUE THREAD

**Issue by alexlancaster** [alexlancaster/pypop#3]
@sjmack @kosoegawa

**Comment by alexlancaster** [comment]
Hi Steve, could you attach a sample of where an addition of the colon breaks the processing or output, this will help with unit testing.  @sjmack

**Comment by alexlancaster** [comment]
Don't worry, I found one in the Synth_Pop_Dataset.

**Comment by sjmack** [comment]
I don't see that dataset in /data. Where is it?

**Comment by alexlancaster** [comment]
It's not yet committed (GitHub don't like large data files in repositories, there is an alternative service for that). It's the one you sent me via email.

**Comment by sjmack** [comment]
Can we make it available online somewhere other than github so that others of us who may want to use it can have access to it? We can send the link around via email.

**Comment by alexlancaster** [comment]
Yes, GitHub has another service for that purpose as well. It may also be OK for the repo, will check tomorrow, mainly they don't like having files in the gigabyte range.

**Comment by sjmack** [comment]
The Synth_PyPop_Dataset.txt file is only 1.44MB.

**Comment by sjmack** [comment]
Here's the error that I get when I try to run any of the HWE functions using colon-delimited data (the Synth PyPop dataset) on a PyPop v0.7.0 PC install: 

```
C:\Program Files (x86)\PyPopWin32-0.7.0>pypop-batch -c 20loci.ini Synth_PyPop_Dataset.pop
LOG: Data file has no header data block
Traceback (most recent call last):
  File "<string>", line 335, in <module>
  File "/cygdrive/c/Documents and Settings/alexl.EEBWEB/src/allele5.biol.berkele
y.edu/ihwg/src/buildstandalone/out1.pyz/Main", line 415, in __init__
  File "/cygdrive/c/Documents and Settings/alexl.EEBWEB/src/allele5.biol.berkele
y.edu/ihwg/src/buildstandalone/out1.pyz/Main", line 661, in _doGenotypeFile
  File "/cygdrive/c/Documents and Settings/alexl.EEBWEB/src/allele5.biol.berkele
y.edu/ihwg/src/buildstandalone/out1.pyz/HardyWeinberg", line 124, in __init__
  File "/cygdrive/c/Documents and Settings/alexl.EEBWEB/src/allele5.biol.berkele
y.edu/ihwg/src/buildstandalone/out1.pyz/HardyWeinberg", line 227, in _generateTa
bles
KeyError: '01'

```

**Comment by alexlancaster** [comment]
@sjmack when you've had a chance to get things working on ```master```, try switching to the  ```allele-colon``` branch using ```git checkout allele-colon``` and try the following:

```
./bin/pypop.py -c data/ihiws2017/Test_Allele_Colon_HardyWeinberg.ini data/ihiws2017/Test_Allele_Colon_HardyWeinberg.pop
```

This tests the HardyWeinberg module can handle colons in alleles.  The input file is based on a one locus of the SynthPop dataset, with only 20 alleles.  It would be good to create similar ones to this.  note that this only handles allele counts with the HardyWeinberg module. We will write separate tests / with separate input files for each of the features and/or classes.

**Comment by sjmack** [comment]
Okay! This works on my new machine! 

However, I note that in the updated instructions, "Installation 1. Install OS-specific tools /5. Check that the MacPorts version ...." users are supposed to check for the MacPorts python install before python has been installed in "4. Install external dependencies". 

Also, the install instructions in the allele-colon branch discuss pip, but I don't have pip after following that procedure.

**Comment by alexlancaster** [comment]
Good catch on the order! I'll fix that.

For pip, you should add the package py27-pip to the list of MacPorts packages. I'll fix that too shortly.

**Comment by alexlancaster** [comment]
OK, @sjmack  this should be fixed.  By the way, I've moved all the data used in the unit / pipeline tests under ```tests/data```, so you should run the following to test:

```
./bin/pypop.py -c tests/data/Test_Allele_Colon_HardyWeinberg.ini tests/data/Test_Allele_Colon_HardyWeinberg.pop
```

I've also incorporated the above into a proper automated test, so if you've installed ```pytest``` as per the updated README.md for this branch you should be able run any of the new tests automatically using the following:

```
pytest
```

You can also run them individually (like the allele colon test) like this:

```
pytest tests/test_AlleleCount.py
```

What this does it to compare the .txt output with a gold standard output using md5sum to check file contents.

**Comment by sjmack** [comment]
The instruction order also has to be changed in the master branch README.

**Comment by alexlancaster** [comment]
Yep, I'll be merging this branch to master soon.

**Comment by alexlancaster** [comment]
I made a new push, since I changed some C code you'll need to rebuild after this push: ```setup.py build```

**Comment by sjmack** [comment]
Built and tested successfully. 

However pytest does not work for me ...

:pypop sjmack$ sudo port select --set pip pip27
Selecting 'pip27' for 'pip' succeeded. 'pip27' is now active.
:pypop sjmack$ pip install --user pytest
Collecting pytest
  Downloading pytest-3.1.2-py2.py3-none-any.whl (180kB)
    100% |████████████████████████████████| 184kB 3.1MB/s 
Requirement already satisfied: setuptools in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pytest)
Collecting py>=1.4.33 (from pytest)
  Downloading py-1.4.34-py2.py3-none-any.whl (84kB)
    100% |████████████████████████████████| 92kB 4.7MB/s 
Installing collected packages: py, pytest
Successfully installed py-1.4.34 pytest-3.1.2
:pypop sjmack$ pytest
bash: pytest: command not found

**Comment by alexlancaster** [comment]
Can you run ```which pytest```?  Try also ```py.test```.  You might also need to restart your terminal.  Also what is the output of ```echo $PATH```? I believe ```pip``` _should_ put ```/Users/<username>/.local/bin``` into your ```$PATH``` environment variable, but it's possible you need to make that manual modification to ```~/.bash_profile```.  By the way, this isn't something that users should need to run (which is why it's not yet in the ```README.md```), but it will be handy to run as we do the testing.

**Comment by sjmack** [comment]
```
:pypop sjmack$ which pytest
:pypop sjmack$ 
```
```
:pypop sjmack$ py.test
-bash: py.test: command not found
```
```
:pypop sjmack$ which py.test
:pypop sjmack$ 
```
```
:pypop sjmack$ echo $PATH
/opt/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin

```
I don't have a /Users/sjmack/.local directory....
```
:~ sjmack$ ls -al /Users/sjmack/.local
ls: /Users/sjmack/.local: No such file or directory
```

**Comment by alexlancaster** [comment]
Try re-running: ```pip install --user pytest```  if it's installed correctly you should see something like:

```
equirement already satisfied (use --upgrade to upgrade): pytest in /mnt/hgfs-mac/fedora/home/alex/.local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.33 in /mnt/hgfs-mac/fedora/home/alex/.local/lib/python2.7/site-packages (from pytest)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from pytest)
```

**Comment by sjmack** [comment]
```
:pypop sjmack$ pip install --user pytest
Requirement already satisfied: pytest in /Users/sjmack/Library/Python/2.7/lib/python/site-packages
Requirement already satisfied: setuptools in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pytest)
Requirement already satisfied: py>=1.4.33 in /Users/sjmack/Library/Python/2.7/lib/python/site-packages (from pytest)
```

**Comment by alexlancaster** [comment]
Don't worry about the pytest framework for the moment. Try to run the test manually:

./bin/pypop.py -m -c ./tests/data/Test_Allele_Colon_HardyWeinberg.ini ./tests/data/Test_Allele_Colon_HardyWeinberg.pop'

I just noticed a MacOS specific issue I may need to fix, so it may crash. Sheesh, all of you non-Linux users, going around making our lives difficult :)

**Comment by sjmack** [comment]
That works just fine! :)

**Comment by alexlancaster** [comment]
Excellent, I was going to say that might also need to remove the ```build``` directory by running:

```./setup.py clean``` 

and also removing all the C modules files:

 ```rm _*.so```

**Comment by alexlancaster** [comment]
To get ```pytest``` working you should make sure that:

```/Users/sjmack/Library/Python/2.7/bin```

is in your ```PATH``` variable. e.g. my ```~/.bash_profile``` has:

```export PATH=/opt/local/bin:$HOME/Library/Python/2.7/bin:$PATH```

if this turns out to be needed for ```pip```.  I'll add them to the instructions in a separate section on testing, since most users shouldn't need to run ```pytest```.

**Comment by sjmack** [comment]
Okay. Adding that to the PATH worked. However, now I am getting pytest errors: 

```
:pypop sjmack$ pytest
====================================================== test session starts =======================================================
platform darwin -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Applications/PyPop/pypop, inifile:
collected 1 items / 1 errors 

============================================================= ERRORS =============================================================
______________________________________________ ERROR collecting tests/test_gthwe.py ______________________________________________
ImportError while importing test module '/Applications/PyPop/pypop/tests/test_gthwe.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_gthwe.py:4: in <module>
    import _Gthwe
E   ImportError: No module named _Gthwe
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================== 1 error in 0.14 seconds =====================================================
:pypop sjmack$ pytest tests/test_AlleleCount.py 
====================================================== test session starts =======================================================
platform darwin -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Applications/PyPop/pypop, inifile:
collected 1 items 

tests/test_AlleleCount.py F

============================================================ FAILURES ============================================================
________________________________________________________ test_AlleleColon ________________________________________________________

    def test_AlleleColon():
        process=subprocess.Popen(
            ['./bin/pypop.py', '-m', '-c', './tests/data/Test_Allele_Colon_HardyWeinberg.ini', './tests/data/Test_Allele_Colon_HardyWeinberg.pop'],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT
            )
        process.communicate()
        exit_code = process.wait()  # wait until script completed
    
        # check exit code
>       assert exit_code == 0
E       assert 1 == 0

tests/test_AlleleCount.py:15: AssertionError
==================================================== 1 failed in 0.07 seconds ====================================================

```

**Comment by alexlancaster** [comment]
running the same command outside the test harness works?

```
./bin/pypop.py -m -c ./tests/data/Test_Allele_Colon_HardyWeinberg.ini ./tests/data/Test_Allele_Colon_HardyWeinberg.pop
```

**Comment by alexlancaster** [comment]
try also running the test using the console output mode:

```
 pytest -s tests/test_AlleleCount.py 
```

**Comment by alexlancaster** [comment]
ensure that your build is also up to date: ```./setup.py build```

**Comment by sjmack** [comment]
Yeah, I had to do a build. I must have forgotten to somewhere between pulls and checkouts. 

So pytest starts now, but Python is crashing on my system, and I 'm getting a "Report Problem to Python" window.

```
:pypop sjmack$ pytest
===================================================================================== test session starts ======================================================================================
platform darwin -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Applications/PyPop/pypop, inifile:
collected 2 items 

tests/test_AlleleCount.py F
tests/test_gthwe.py Abort trap: 6
```

The pypop test runs fine outside of pytest though.

I'll email you the python crash report...

**Comment by alexlancaster** [comment]
I think the test_gthwe.py is broken, I should disable for the moment (I suspect that's generating the crash output). Eventually the test framework will hook into setup and you can just run setup.py test, and it will do the build for you as well,but we're not there yet.  

Right now I want to know about the allele colon test, try just running it alone:

py.test -s tests/test_AlleleColon.py

**Comment by sjmack** [comment]
There is no tests/test_AlleleColon.py script, but I tested `py.test -s tests/test_AlleleCount.py` and got failures.

```
:pypop sjmack$ py.test -s tests/test_AlleleCount.py 
===================================================================================== test session starts ======================================================================================
platform darwin -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Applications/PyPop/pypop, inifile:
collected 1 items 

tests/test_AlleleCount.py F

=========================================================================================== FAILURES ===========================================================================================
_______________________________________________________________________________________ test_AlleleColon _______________________________________________________________________________________

    def test_AlleleColon():
        process=subprocess.Popen(
            ['./bin/pypop.py', '-m', '-c', './tests/data/Test_Allele_Colon_HardyWeinberg.ini', './tests/data/Test_Allele_Colon_HardyWeinberg.pop'],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT
            )
        process.communicate()
        exit_code = process.wait()  # wait until script completed
    
        # check exit code
        assert exit_code == 0
        # compare with md5sum of output file
>       assert hashlib.md5(open("Test_Allele_Colon_HardyWeinberg-out.txt", 'rb').read()).hexdigest() == '59c5f520b7700ac4fde03aac93640460'
E       AssertionError: assert '288784d1e942...ec695b9d3c1d7' == '59c5f520b7700...03aac93640460'
E         - 288784d1e942c7a6dddec695b9d3c1d7
E         + 59c5f520b7700ac4fde03aac93640460

tests/test_AlleleCount.py:17: AssertionError
================================================================================== 1 failed in 27.83 seconds ===================================================================================
```

```
:pypop sjmack$ ls tests/
__pycache__		base.py			base.pyc		data			test_AlleleCount.py	test_gthwe.py
```

```
:pypop sjmack$ git pull
Your configuration specifies to merge with the ref 'refs/heads/allele-colon'
from the remote, but no such ref was fetched.
```
```
:pypop sjmack$ git checkout
Your branch is up-to-date with 'origin/allele-colon'.
```

**Comment by alexlancaster** [comment]
Yep, should rename that. Try:

git checkout master
git pull

The all-colon branch is now merged back with master

**Comment by alexlancaster** [comment]
Oh, and rebuild again. :)

Basically get used to doing builds as a habit even if I don't explicitly say to do it, especially during this phase of rapid development. :)

**Comment by sjmack** [comment]
Done. `py.test -s tests/test_AlleleCount.py` passed in 3.55s.

**Comment by alexlancaster** [comment]
I updated master branch to make the test name correct and it skips the broken test for the moment.  ```git pull``` and re-run ```py.test``` (I also updated the docs with a new section on running tests, since a basic installation doesn't need ```pytest```)

**Comment by sjmack** [comment]
No Joy. :(

```
:pypop sjmack$ py.test -s tests/test_AlleleColon.py 
===================================================================================== test session starts ======================================================================================
platform darwin -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Applications/PyPop/pypop, inifile:
collected 1 items 

tests/test_AlleleColon.py F

=========================================================================================== FAILURES ===========================================================================================
_______________________________________________________________________________________ test_AlleleColon _______________________________________________________________________________________

    def test_AlleleColon():
        process=subprocess.Popen(
            ['./bin/pypop.py', '-m', '-c', './tests/data/Test_Allele_Colon_HardyWeinberg.ini', './tests/data/Test_Allele_Colon_HardyWeinberg.pop'],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT
            )
        process.communicate()
        exit_code = process.wait()  # wait until script completed
    
        # check exit code
>       assert exit_code == 0
E       assert 1 == 0

tests/test_AlleleColon.py:16: AssertionError
=================================================================================== 1 failed in 0.12 seconds ===================================================================================

```

**Comment by alexlancaster** [comment]
Try running the same command manually. You had this working earlier, no?

**Comment by sjmack** [comment]
That (`py.test -s tests/test_AlleleColon.py`) is the same exact command that I ran successfully yesterday at 3:08PM PDT.

**Comment by sjmack** [comment]
With the exception that the name of test_AlleleCount.py was changed to test_AlleleColon.py.

**Comment by alexlancaster** [comment]
Try running outside the test harness and/or doing a rebuild.

**Comment by sjmack** [comment]
Okay. After a pull and build in the master branch, I get the same error for py.test and following error for the manual test: 

```
:pypop sjmack$ ./bin/pypop.py -m -c ./tests/data/Test_Allele_Colon_HardyWeinberg.ini ./tests/data/Test_Allele_Colon_HardyWeinberg.pop
Traceback (most recent call last):
  File "./bin/pypop.py", line 123, in <module>
    from PyPop.Main import getUserFilenameInput, checkXSLFile
  File "/Applications/PyPop/pypop/bin/../PyPop/Main.py", line 45, in <module>
    from HardyWeinberg import HardyWeinberg, HardyWeinbergGuoThompson, HardyWeinbergGuoThompsonArlequin, HardyWeinbergEnumeration
  File "/Applications/PyPop/pypop/bin/../PyPop/HardyWeinberg.py", line 42, in <module>
    import _Pvalue
ImportError: No module named _Pvalue
```

**Comment by alexlancaster** [comment]
You definitely need to rebuild.  You are probably missing a file _Pvaluemodule.so in your top-level directory.

**Comment by alexlancaster** [comment]
Also what is the current working directory for your git repository checkout?

pwd

**Comment by sjmack** [comment]
_Pvaluemodule.so was deleted via `rm _*.so`. I was cleaning up, as you recommended yesterday, after each build.  `:D`

Looks like everything is working now. 

```
pypop sjmack$ pwd
/Applications/PyPop/pypop
```

```
pypop sjmack$ pytest
======================================================================================= test session starts ========================================================================================
platform darwin -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Applications/PyPop/pypop, inifile:
collected 2 items 

tests/test_AlleleColon.py .
tests/test_gthwe.py s

=============================================================================== 1 passed, 1 skipped in 3.87 seconds ================================================================================

```
```
:pypop sjmack$ py.test -s tests/test_AlleleColon.py 
======================================================================================= test session starts ========================================================================================
platform darwin -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Applications/PyPop/pypop, inifile:
collected 1 items 

tests/test_AlleleColon.py .

===================================================================================== 1 passed in 3.85 seconds =====================================================================================
```
Running outside the test harness works fine.

**Comment by alexlancaster** [comment]
test should work now, if it looks OK to you, feel free to close.

**Comment by sjmack** [comment]
I don't have a comment and close button for this Issue, but okay to close.
