### ISSUE TITLE
Popmeta 3-locus-summary.dat files have missing headers/extra columns/columns out of order

### ISSUE THREAD

**Issue by sjmack** [alexlancaster/pypop#31]
`./bin/pypop.py --generate-tsv -c WS_BDCtrl_Test_EM_lite.ini BIGDAWG_SynthControl_Data.pop` in which [Emhaplofreq] has `LociToEstHaplo=a:drb1:drb3` generates the following 3-locus-summary.dat file: 

```
n.gametes       locus1  locus2  locus3
0       ****    ****    ****    ****    ****    ****    ****    ****    1982    DRB3    A       DRB1    ****    
:pypop sjmack$ more WS_BDCtrl_Test_EM_lite.ini
```
Which includes 8 extra fields in the data block, and 7 spaces in the header block between the "n.gametes" and "locus1" column names. There is also an extra field after the Locus3 field. 

the n.gametes field should correspond to the 1982 data, so that column name is really far out of place. 

When I add the DQB1_1 and DQB1_2 loci to validSampleFields and set [Emhaplofreq] to `LociToEstHaplo=a:drb1:drb3:dqb1` in the .ini, the 4-locus-summary.dat file looks like this: 

```
pop     labcode method  ethnic  collect.site    region  latit   longit  complex n.gametes       locus1  locus2  locus3  locus4
0       ****    ****    ****    ****    ****    ****    ****    ****    1982    DRB3    A       DRB1    DQB1    ****    

```
Here, the ihwg column names appear in the header. This makes it (relatively clear) that the data for the pop field is 0 (which corresponds to Disease in the .pop file, which is identified as the popNameDesignator in the .ini). However, this identifier (pop or popname, below) is missing in the 3-locus-summary.dat file. 

When I run `./bin/popmeta.py --disable-ihwg *-out.xml` the 4-locus-summary.dat file looks like this: 

```
popname n.gametes       locus1  locus2  locus3  locus4
0       1982    DRB3    A       DRB1    DQB1    ****    
```

Here all of the column headers have corresponding data in the data-block, but there is an extraneous "****" after the locus4 column, with no column header. 

It seems like the column headers for these files need to be reorganized. 

1. The extra **** data in the last (unnamed) column needs to be removed in both the 3-locus and 4-locus summary files. 

2. The ihwg column names need to be added to the (currently) default header for the 3-locus-summary.dat file. 

3. There are a lot of extraneous spaces in the header between the names of several columns. I'm not sure if this is a bug or an attempt to space things out. Someone should look at it though.

**Comment by sjmack** [comment]
Oh, and the 3-locus-summary.dat file generated via `./bin/popmeta.py --disable-ihwg *-out.xml` when [Emhaplofreq] is set to LociToEstHaplo=a:drb1:drb3

Is still missing the popname column name. 

```
n.gametes       locus1  locus2  locus3
0       1982    DRB3    A       DRB1    ****    
```

So 4. Add `popname` as the column name for the first column in the 3-locus-summary.dat file when --disable-ihwg is passed to popmeta.

**Comment by alexlancaster** [comment]
#67 didn't close this issue

**Comment by alexlancaster** [comment]
This looks to be a pretty straightforward bug in the XSLT.  I've made a branch and will make a PR soon that hopefully fixes this.

**Comment by alexlancaster** [comment]
PR #106 should fix this:
 
>   1. The extra **** data in the last (unnamed) column needs to be removed in both the 3-locus and 4-locus summary files.

This is actually a missing column header `metaloci` - so I added it to the header, rather than remove it from each line in the output.  It's useful if output is generated by the `Sequence` module, so that each amino-acid "locus" can be tied back to the original upstream gene-level locus. A metaloci is not generated in the default output, but there's no harm to having an extra "NA" column, so long as it's labelled.
 
>   2. The ihwg column names need to be added to the (currently) default header for the 3-locus-summary.dat file.

Done.

>   3. There are a lot of extraneous spaces in the header between the names of several columns. I'm not sure if this is a bug or an attempt to space things out. Someone should look at it though.

I think that's just how it looks on the terminal - there seems to be only tabs between each column, which is how it should be.

>   4. Add `popname` as the column name for the first column in the 3-locus-summary.dat file when --disable-ihwg is passed to popmeta.

Added.

**Comment by alexlancaster** [comment]
> When I add the DQB1_1 and DQB1_2 loci to validSampleFields and set [Emhaplofreq] to `LociToEstHaplo=a:drb1:drb3:dqb1` in the .ini, the 4-locus-summary.dat file looks like this:
> 
> ```
> pop     labcode method  ethnic  collect.site    region  latit   longit  complex n.gametes       locus1  locus2  locus3  locus4
> 0       ****    ****    ****    ****    ****    ****    ****    ****    1982    DRB3    A       DRB1    DQB1    ****    
> ```

I also added a unit test for the 4 locus case to mirror this test.
