### ISSUE TITLE
HaploStats doesn't report correct low frequency haplotypes

### ISSUE THREAD

**Issue by sjmack** [alexlancaster/pypop#38]
See my final [comment](https://github.com/alexlancaster/pypop/issues/28#issuecomment-324105369) in [Issue #28](https://github.com/alexlancaster/pypop/issues/28). 

`<haplostats>` is reporting converged haplotype frequency estimates differently from `<emhaplofreq>`, is not reporting haplotype counts, and is truncating frequencies that were returned in scientific E-notation to eliminate the exponent.

**Comment by alexlancaster** [comment]
see fuller description of issue here: https://github.com/alexlancaster/pypop/issues/60#issue-1713127797 and proposed solution here: https://github.com/alexlancaster/pypop/issues/60#issuecomment-1560102886

**Comment by alexlancaster** [comment]
@sjmack looking at this issue, it seems that the low frequency truncation is actually separate to the lack of counts.  I would open up another issue for the numbers of copies.

quick review of the code suggests it was disabled in the XML output pending a check of the numbers, there's a FIXME:

https://github.com/alexlancaster/pypop/blob/main/src/PyPop/Haplo.py#L1013

**Comment by alexlancaster** [comment]
@sjmack When you open up a new issue, I'd remove the comment in the code and re-run, and check to see if the copies are calculated correctly.  if so, we can probably uncomment and add it.  We should also unit tests for haplo-stats, so a self-contained `.ini` and `.pop` that I can use for that purpoes, would be really helpful.

**Comment by alexlancaster** [comment]
@sjmack I made a branch to test this fix.  in your local git clone you can pull it and rebuild to test it on your data:

```
git pull
git checkout 38-problem-with-haplostats-implementation
````

if it works for you an passes all the unit tests I'll merge it with main.

**Comment by alexlancaster** [comment]
@sjmack check out the pull request #61 (see above for instructions forbuidling  and give me an :+1: or :-1:  )

as I mentioned on the pull request it would be good to be able get a unit test to go along with this, if possible.

**Comment by alexlancaster** [comment]
splitting off the count issue as a new issue in #65 and retitling this issue

**Comment by sjmack** [comment]
@alexlancaster I will try to get to this later this week. Sorry for the delay.

**Comment by alexlancaster** [comment]
@sjmack opened up a new issue #104 for preserving scientific notation when truncating.
