### ISSUE TITLE
Problem with pypop-haplostats 

### ISSUE THREAD

**Issue by LCreary** [alexlancaster/pypop#39]
I encountered a problem when trying to run the test minimal ini file and sample population dataset using the container Karl built. The problem seems to be a source code error

![image](https://user-images.githubusercontent.com/26468019/29639999-b30f900c-8811-11e7-89c2-14fb33488554.png)

**Comment by afadda91** [comment]
I also have problems with this function. I used the [Haplostats] function with lociToEstHaplo=* but it only reports haplotypes for 4 genes max
When I try to use lociToEstHaplo for more than 4 genes, it only calculates 3 or 4 genes i don't know what it depends on.

**Comment by alexlancaster** [comment]
Not sure if these comments relate to the original problem reported, and if this is still an issue.  If somebody can provide a full test case with an `.ini` and `.pop` file soon, I'll try and work on it.  If not, I will close it.

**Comment by alexlancaster** [comment]
Closing this issue as obsolete, but you can always re-open a new issue if you can reproduce errors with the new version.
