### ISSUE TITLE
Problem with Emhaplofreq LD calculations

### ISSUE THREAD

**Issue by sjmack** [alexlancaster/pypop#40]
The Wn and D' values being returned by [Emhaplofreq] for `./bin/pypop.py -c minimal.ini sample.pop` (using the attached files) are >1, but they should range from 0 to 1. See below. 

I know that [Emhaplofreq] is depreciated, but it seems like this indicates that something is broken in it. 

```
Pairwise LD estimates
---------------------
Locus pair            D      D'        Wn   ln(L_1)   ln(L_0)         S # permu p-value
A:C             0.06126 1.37143   1.63299   -289.09   -246.03    -86.13       - -      
A:B             0.05896 1.37143   1.63299   -293.47   -244.64    -97.66       - -      
A:DRB1          0.05266 1.24762   2.33631   -282.00   -272.35    -19.32       - -      
A:DQA1          0.05875 1.24762   2.86138   -269.57   -274.43      9.71       - -      
A:DQB1          0.04204 1.13675   3.64692   -275.58   -336.12    121.06       - -      
A:DPA1          0.12862 2.30779   2.36391   -219.78   -178.36    -82.83       - -      
A:DPB1          0.07316 1.38957   1.98626   -237.85   -225.61    -24.49       - -      
C:B             0.07052 1.24704   1.39196   -210.37   -247.53     74.32       - -      
C:DRB1          0.05513 1.27630   2.69649   -280.34   -313.37     66.06       - -      
C:DQA1          0.08671 1.24054   2.18414   -263.23   -240.39    -45.68       - -      
C:DQB1          0.08262 1.24054   1.95355   -269.55   -239.70    -59.70       - -      
C:DPA1          0.12461 1.22826   3.01602   -224.72   -232.31     15.18       - -      
C:DPB1          0.12047 1.46364   1.33749   -242.45   -175.80   -133.31       - -      
B:DRB1          0.04831 1.21417   2.98728   -286.79   -330.85     88.12       - -      
B:DQA1          0.07547 1.21852   2.42613   -271.36   -257.87    -26.98       - -      
B:DQB1          0.07175 1.21852   2.17000   -277.30   -257.18    -40.24       - -      
B:DPA1          0.10938 1.24112   3.36962   -229.76   -250.36     41.20       - -      
B:DPB1          0.10966 1.47727   1.41639   -247.84   -182.99   -129.70       - -      
DRB1:DQA1       0.06273 1.24439   3.46731   -164.06   -323.72    319.31       - -      
DRB1:DQB1       0.05851 1.24439   3.10125   -147.74   -323.03    350.58       - -      
DRB1:DPA1       0.10072 1.27327   5.31875   -202.51   -331.99    258.96       - -      
DRB1:DPB1       0.08588 1.54545   2.17307   -231.03   -255.74     49.42       - -      
DQA1:DQB1       0.08955 1.21277   2.29619   -152.52   -250.05    195.06       - -      
DQA1:DPA1       0.14302 1.23791   3.27044   -185.25   -247.18    123.87       - -      
DQA1:DPB1       0.12423 1.49091   1.84842   -210.93   -196.13    -29.60       - -      
DQB1:DPA1       0.13263 1.23791   3.27044   -193.17   -246.49    106.63       - -      
DQB1:DPB1       0.11754 1.49091   1.65328   -222.73   -195.44    -54.58       - -      
DPA1:DPB1       0.19210 1.45478   2.29742   -165.96   -172.34     12.75       - -      
```

[minimal.ini.txt](https://github.com/alexlancaster/pypop/files/1247995/minimal.ini.txt)
[sample.pop.txt](https://github.com/alexlancaster/pypop/files/1247996/sample.pop.txt)

**Comment by jilorenzo** [comment]
I am using PyPop 0.7.0 to compute LD for HLA loci but some D' values are above 1 (they should range from 0 to 1). The sample size is 1959 (allele count 3918). See below the output.

Pairwise LD estimates
---------------------
Locus pair            D      D'        Wn             ln(L_1)   ln(L_0)         S # permu p-value
A:B               0.00371  0.55762   8.47095 -18948.36 -21522.98   5149.23       - -      
A:C               0.00521  0.45699   0.27777 -17201.80 -18966.47   3529.35       - -      
A:DR            0.00346  0.37996   0.23559 -18908.96 -20181.43   2544.93       - -      
A:DQ            0.00446  0.32337   0.27153 -17004.14 -17775.26   1542.24       - -      
B:C               0.01145  1.55568   0.56710 -15068.88 -21565.51  12993.27       - -      
B:DR             0.00614 0.96327   0.37665 -19829.33 -22771.01   5883.36       - -      
B:DQ            0.01441 1.30787   0.43597 -18524.87 -20420.28   3790.81       - -      
C:DR            0.00423  0.45454   0.26817 -18626.12 -20320.88   3389.52       - -      
C:DQ            0.00488 0.37253   0.30688 -16860.22 -17914.71   2108.98       - -      
DR:DQ          0.01218 0.91521   0.68732 -12646.77 -19129.66  12965.79       - -

**Comment by rsingle** [comment]
Hello. My guess is that there are a large number of very low frequency 
haplotypes and maybe some rounding error involved. Can you send me the 
B:C or B:DQ data so I can take a look?

Thanks,
Rich

-- 
=======================================
Richard M. Single, Ph.D.
Dept. of Mathematics and Statistics
University of Vermont
Burlington, VT 05405
802-656-8631, Richard.Single@uvm.edu
=======================================
