### ISSUE TITLE
PyPop [Filters] not working 

### ISSUE THREAD

**Issue by sjmack** [alexlancaster/pypop#43]
PyPop [Filters] functions aren't working, and are crashing PyPop. 

Here are some examples of what happens when I run `./bin/pypop.py -c sm_bin_minimal.ini sample.pop `using the following options in the .ini file. 

When I include: 
```
[Filters]
;filtersToApply=DigitBinning
filtersToApply=CustomBinning

;[DigitBinning]
;filterType=DigitBinning
;binningDigits=2
```
Using  a .ini file with the above sections alone (and no CustomBinning rules) returns 
```
LOG: Data file has no header data block
Could not parse the CustomBinning rules.
```

However, adding the following to the .ini:
```
[CustomBinning]
A=!****/2401
 !0101/0104/0105/0122
 !0201/0209/0243/0266/0275/0283/0289/0297/02G1
 !0206/9226
 !0207/0215
 !0211/0269/0298
 !0222/0223/9204
 !0296/0298
 !0281/9224
 !0301/0320/0321/0326/03G1
 !1101/1121
 !2301/2307
 !2402/2409/2411/2440/2476/2479/24G1
 !2403/2433
 !2408/2412
 !2601/2624/2626
 !3004/3005
 !3101/3114
 !3108/2416
 !3303/3302
 !6801/6811/6833
 !7401/7402
```

returns: 
```
LOG: Data file has no header data block
Traceback (most recent call last):
  File "./bin/pypop.py", line 336, in <module>
    testMode=testMode)
  File "/Applications/PyPop/pypop/bin/../PyPop/Main.py", line 368, in __init__
    self._runFilters()
  File "/Applications/PyPop/pypop/bin/../PyPop/Main.py", line 541, in _runFilters
    self.matrixHistory.append(filter.doCustomBinning((self.matrixHistory[-1]).copy()))
  File "/Applications/PyPop/pypop/bin/../PyPop/Filter.py", line 945, in doCustomBinning
    if len(individ[i].split("/")) > 1:
AttributeError: 'numpy.ndarray' object has no attribute 'split'
```

Changing the pertinent section of the .ini to:
```
[Filters]
filtersToApply=DigitBinning
;filtersToApply=CustomBinning

[DigitBinning]
filterType=DigitBinning
binningDigits=2
```

Results in:

```
LOG: Data file has no header data block
Traceback (most recent call last):
  File "./bin/pypop.py", line 336, in <module>
    testMode=testMode)
  File "/Applications/PyPop/pypop/bin/../PyPop/Main.py", line 368, in __init__
    self._runFilters()
  File "/Applications/PyPop/pypop/bin/../PyPop/Main.py", line 525, in _runFilters
    self.matrixHistory.append(filter.doDigitBinning((self.matrixHistory[-1]).copy()))
  File "/Applications/PyPop/pypop/bin/../PyPop/Filter.py", line 921, in doDigitBinning
    if allele[i] != self.untypedAllele and len(allele[i]) > self.binningDigits:
TypeError: len() of unsized object
```

I haven't checked all of the [Filters] options, but I suspect that a general repair is needed.

**Comment by alexlancaster** [comment]
@sjmack I'll take a look.  I haven't used the `[Filters]` functionality for a while, and we don't have any unit tests for any of the filters.  It would be useful if you have a self-contained `.ini` and `.pop` I could use to get started on debugging and/or creating a new unit test.

**Comment by alexlancaster** [comment]
I'll open up a PR based on this.  I added a quick unit test based on the `USAFEL-UchiTelle-small.pop` file.  This is likely inadequate because it doesn't really use the `CustomBinning` filters much.  Should add a unit test that uses more of the `CustomBinning` rules.  

@sjmack Can you add a `.pop` sample and `.ini` combination that you used?

**Comment by alexlancaster** [comment]
This error:

> ```
> LOG: Data file has no header data block
> Traceback (most recent call last):
>   File "./bin/pypop.py", line 336, in <module>
>     testMode=testMode)
>   File "/Applications/PyPop/pypop/bin/../PyPop/Main.py", line 368, in __init__
>     self._runFilters()
>   File "/Applications/PyPop/pypop/bin/../PyPop/Main.py", line 541, in _runFilters
>     self.matrixHistory.append(filter.doCustomBinning((self.matrixHistory[-1]).copy()))
>   File "/Applications/PyPop/pypop/bin/../PyPop/Filter.py", line 945, in doCustomBinning
>     if len(individ[i].split("/")) > 1:
> AttributeError: 'numpy.ndarray' object has no attribute 'split'

is due to missing conversion from internal `ndarray` to a `string`, which I fixed in the new branch.  The `DigitBinning` has the same underlying cause.
