### ISSUE TITLE
Input file

### ISSUE THREAD

**Issue by simonecarvalho91** [alexlancaster/pypop#46]
Hi, does anyone have a model of the input file to haplo.stas for me to see?
I have the genotypes for 5 SNPs for 95 samples. I also have 96 samples as control and I want to know the prevalence of haplotypes between samples and if there is any correlation between these two groups. Is there a model of an input file that I can use with the read.table function on R? Thanksssssssssssssssssssss

**Comment by sjmack** [comment]
@simonecarvalho91, this seems like it is outside of the scope of PyPop (and it has been two weeks, so you've probably figured this out), but for Haplo.Stats' haplo.em function, you want an input file with two columns of data per locus, and one row per subject. Like this (where the data in the matrix is HLA allele names, not SNP data, but it doesn't make a difference):

```
a	a	c	c	b	b
0201	2601	0702	0702	0702	3901
2402	3201	0401	1402	1516	3502
0201	3303	0602	0702	0702	5001
```

Then you can pass this into haplo.em as below:

```
> testData <- read.table("haplo_em_sample_data.txt", header=T,sep="\t",colClasses = "character")
> testDataCols <- unique(gsub(".1","",colnames(testData),fixed=TRUE))
> testHapFreqs <- haplo.em(testData,testDataCols,miss.val=0)
```

Good luck!

**Comment by simonecarvalho91** [comment]
oh, thanks.

in the line that we have "a a c c b b" I can put the name/id of the snps? and in the numbers in the columns (ex: 0201, 2601... that I understood that was the hla allele names) I put my genotype for that SNP? Or I am wrong?

**Comment by sjmack** [comment]
Thats all correct. The locus/SNP names don't *have* to be the column names of that file, but it is convenient to store them that way.

You can  look at section 3 of the [Haplo.Stats vignette](https://cran.r-project.org/web/packages/haplo.stats/vignettes/manualHaploStats.pdf) for more details on using haplo.em.
