### ISSUE TITLE
PyPop Data formats vs HLA nomenclature "formats"

### ISSUE THREAD

**Issue by sjmack** [alexlancaster/pypop#5]
We should make sure that we are on the same page when talking about "format" for loading data into PyPop. Currently, PyPop 0.7.0 supports genotype data in a tab-delimited format, and only fully supports HLA data using IPD-IMGT/HLA Database version 2.x.x alleles (or lower). 

Including HLA alleles from IPD-IMGT/HLA Database version 3.x.x results in the following issues. 
1. Hardy-Weinberg tests performed on these data cause PyPop to crash. These data have to have the colons removed in order to do HW tests with PyPop.

2. Haplotype results are delimited using colons. This makes it very difficult to read haplotype results when the input data have colons in them. 

Suggested solutions: 

1. Fix the HW module so that colons in the allele names don't break it. 

2. Use the GL string phase delimiter (~) for returning haplotype results.

**Comment by alexlancaster** [comment]
fixing this means fixing #3  and #4

**Comment by alexlancaster** [comment]
paper on GL string format for reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3715123/

**Comment by alexlancaster** [comment]
Hi @sjmack are there are formatting changes (outside the scope of #3 and #4) that are high-priority for this current update?  If not, I'll go ahead and close this issue.

**Comment by sjmack** [comment]
I think that these are the key format issues that need to be addressed now.
