### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by samuelkyobe** [alexlancaster/pypop#53]
Hi Alex

I have installed pypop on my mac. I have updated almost everything with Catalina. I get the following error.

________________________________________________________ test_AlleleColon_Emhaplofreq ________________________________________________________

    def test_AlleleColon_Emhaplofreq():
    
        exit_code = base.run_pypop_process('./tests/data/Test_Allele_Colon_Emhaplofreq.ini', './tests/data/Test_Allele_Colon_Emhaplofreq.pop')
        # check exit code
        assert exit_code == 0
        # compare with md5sum of output file
>       assert hashlib.md5(open("Test_Allele_Colon_Emhaplofreq-out.txt", 'rb').read()).hexdigest() == '598954bfe301d5dea44ccd4d443905d1'
E       AssertionError: assert '0434be553e01...190107fa48035' == '598954bfe301d...ccd4d443905d1'
E         - 0434be553e01a165994190107fa48035
E         + 598954bfe301d5dea44ccd4d443905d1

tests/test_AlleleColon.py:19: AssertionError
________________________________________________________________ test_USAFEL _________________________________________________________________

    def test_USAFEL():
        exit_code = base.run_pypop_process('./tests/data/minimal.ini', './tests/data/USAFEL-UchiTelle-small.pop')
        # check exit code
        assert exit_code == 0
    
        out_filename = "USAFEL-UchiTelle-small-out.txt"
        gold_out_filename = os.path.join('./tests/data/output', out_filename)
>       assert filecmp.cmp(out_filename, gold_out_filename)
E       AssertionError: assert False
E        +  where False = <function cmp at 0x10c106dd0>('USAFEL-UchiTelle-small-out.txt', './tests/data/output/USAFEL-UchiTelle-small-out.txt')
E        +    where <function cmp at 0x10c106dd0> = filecmp.cmp

tests/test_USAFEL.py:15: AssertionError
========================================= 2 failed, 22 passed, 2 skipped, 1 xfailed in 62.93 seconds =========================================

**Comment by alexlancaster** [comment]
Thanks for the report.  Traced this down to a minor change in the output that trips up two unit tests, working on a fix to the unit tests now.
