### ISSUE TITLE
build bug 

### ISSUE THREAD

**Issue by masen0407** [alexlancaster/pypop#54]
Hello @alexlancaster ,when i try build on macos  11.1
./setup.py build
WARNING: The wheel package is not available.
running build
running build_py
creating build/lib.macosx-11.0-x86_64-2.7
creating build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/HardyWeinberg.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/Arlequin.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/GUIApp.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/ParseFile.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/Homozygosity.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/__init__.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/Haplo.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/DataTypes.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/Utils.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/Filter.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/RandomBinning.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/Main.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
copying PyPop/Meta.py -> build/lib.macosx-11.0-x86_64-2.7/PyPop
running build_ext
building '_Emhaplofreqmodule' extension
swigging emhaplofreq/emhaplofreq_wrap.i to emhaplofreq/emhaplofreq_wrap_wrap.c
swig -python -ISWIG -o emhaplofreq/emhaplofreq_wrap_wrap.c emhaplofreq/emhaplofreq_wrap.i
creating build/temp.macosx-11.0-x86_64-2.7
creating build/temp.macosx-11.0-x86_64-2.7/emhaplofreq
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/openssl/include -D__SWIG__=1 -DDEBUG=0 -DEXTERNAL_MODE=1 -DXML_OUTPUT=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -I/opt/local/include -I/opt/local/include -Iemhaplofreq -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c emhaplofreq/emhaplofreq_wrap_wrap.c -o build/temp.macosx-11.0-x86_64-2.7/emhaplofreq/emhaplofreq_wrap_wrap.o
emhaplofreq/emhaplofreq_wrap_wrap.c:3255:17: error: implicit declaration of function 'main_proc' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  result = (int)main_proc(arg1,(char (*)[20*2][22])arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13);
                ^
emhaplofreq/emhaplofreq_wrap_wrap.c:3196:12: warning: variable 'arg2' is uninitialized when used here [-Wuninitialized]
      free(arg2);
           ^~~~
emhaplofreq/emhaplofreq_wrap_wrap.c:3090:25: note: initialize the variable 'arg2' to silence this warning
  char (*arg2)[20*2][22] ;
                        ^
                         = NULL
1 warning and 1 error generated.
error: command '/usr/bin/clang' failed with exit status 1

echo $CPATH
/opt/local/include:/opt/local/include:
echo $LIBRARY_PATH
/opt/local/lib/:/opt/local/lib/:
echo $PATH
/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Apple/usr/bin:/opt/local/bin:/Users/masen/miniconda3/bin:/Users/masen/miniconda3/condabin:/usr/local/mysql/bin:/usr/local/mysql/bin
which python
/opt/local/bin/python
 port installed
The following ports are currently installed:
  bzip2 @1.0.8_0 (active)
  cython_select @0.1_1 (active)
  db48 @4.8.30_4 (active)
  expat @2.2.10_0 (active)
  fftw-3 @3.3.8_1 (active)
  gettext @0.19.8.1_2 (active)
  gsl @2.6_0 (active)
  icu @67.1_2 (active)
  libedit @20191231-3.1_0 (active)
  libffi @3.3_1 (active)
  libgcc @3.0_0 (active)
  libgcc10 @10.2.0_3 (active)
  libiconv @1.16_1 (active)
  libxml2 @2.9.10_1 (active)
  libxslt @1.1.34_4 (active)
  ncurses @6.2_0 (active)
  nosetests_select @0.1_0 (active)
  OpenBLAS @0.3.12_0+gcc10+lapack (active)
  openssl @1.1.1i_0 (active)
  pcre @8.44_1 (active)
  pip_select @0.1_2 (active)
  py-libxml2 @2.9.10_0 (active)
  py-setuptools @50.3.1_0 (active)
  py27-cython @0.29.13_0 (active)
  py27-libxml2 @2.9.10_0 (active)
  py27-libxslt @1.1.34_0 (active)
  py27-nose @1.3.7_1 (active)
  py27-numpy @1.16.6_2+gfortran+openblas (active)
  py27-pip @20.3.3_0 (active)
  py27-setuptools @44.1.1_0 (active)
  py38-libxml2 @2.9.10_0 (active)
  py39-setuptools @50.3.1_0 (active)
  python2_select @0.0_3 (active)
  python3_select @0.0_2 (active)
  python27 @2.7.18_2 (active)
  python38 @3.8.6_0 (active)
  python39 @3.9.1_0 (active)
  python_select @0.3_9 (active)
  sqlite3 @3.34.0_0 (active)
  swig @4.0.2_1 (active)
  swig-python @4.0.2_1 (active)
  swig3 @3.0.12_2 (active)
  swig3-python @3.0.12_2 (active)
  xz @5.2.5_0 (active)
  zlib @1.2.11_0 (active)

Can u help me
[error.txt](https://github.com/alexlancaster/pypop/files/5733445/error.txt)

**Comment by odoublewen** [comment]
> error: command '/usr/bin/clang' failed with exit status 1

Sounds like you don't have a compiler, which you need to build and install many python packages.   You need to install Apple's Xcode Command Line Tools.

**Comment by odoublewen** [comment]
Hmmm, looking at your question more detail, it seems like a compiler is not the problem.   So, not sure.  I'll try to install on my mac sometime soon.

**Comment by alexlancaster** [comment]
@masen0407 did you manage to fix your problem after all?  If so, would be good to know what the problem was so that we can help other users avoid it.  Cheers

**Comment by masen0407** [comment]
@alexlancaster Thank you for you reply.
i try on a old version Macos PC(v10.15.7 ) and it work ,so i guess maybe it cause by macos system.
so far i can not build pypop on MAC(v11.1).
