### ISSUE TITLE
Error getting PyPop to run on a Mac

### ISSUE THREAD

**Issue by sjmack** [alexlancaster/pypop#9]
I've followed the install instructions, but I am getting the following error with Numeric when trying to run pypop on a Mac running MacOS 10.01.5:

:pypop sjmack$ ./pypop.py
Traceback (most recent call last):
  File "./pypop.py", line 136, in <module>
    from Main import getUserFilenameInput, checkXSLFile
  File "/Applications/PyPop/pypop/Main.py", line 41, in <module>
    from ParseFile import ParseGenotypeFile, ParseAlleleCountFile
  File "/Applications/PyPop/pypop/ParseFile.py", line 44, in <module>
    from Utils import getStreamType, StringMatrix, OrderedDict, TextOutputStream
  File "/Applications/PyPop/pypop/Utils.py", line 43, in <module>
    import Numeric
ImportError: No module named Numeric

**Comment by alexlancaster** [comment]
Hi Steve, can you provide the info in:  https://github.com/alexlancaster/pypop#bug-reporting  ?

**Comment by alexlancaster** [comment]
The key is to make sure that ```Numeric``` is installed and that you are using the **macports** version of Python, not the **system** version of Python.  If you type ```which python``` it should be something like ```/opt/local/bin/python```

**Comment by sjmack** [comment]
Here you go:
:pypop sjmack$ which python
/usr/bin/python
:pypop sjmack$ echo $CPATH
/opt/local/include:
:pypop sjmack$ echo $LIBRARY_PATH
/opt/local/lib/:
:pypop sjmack$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/X11/bin:/opt/local/bin:/opt/local/sbin:/opt/localsbin

I had to set an alias in order to use the MacPort python: 
:pypop sjmack$ sudo ln -s /opt/local/bin/python /usr/local/bin/ppython

So now "ppython ./pypop.py" works. 

However, "sudo port select --set python python27" doesn't seem to be pointing me to the MacPort python. It looks like I have an apple version of python27 as well as the MacPort version.

:pypop sjmack$ port select --list python
Available versions for python:
	none
	python26-apple
	python27 (active)
	python27-apple

I don't know if this is something specific to my setup. *shrug* If not, maybe the Mac install instructions need to be modified.

**Comment by alexlancaster** [comment]
```/opt/local/bin``` should appear before ```/usr/bin``` in your ```PATH``` environment variable, otherwise it will pickup the system Python.  The ````port --set``` command seems to set the version of Python within that MacPorts presents to the user, but doesn't, in itself, switch between MacPorts and the system Python, ```PATH``` does that.

What's the contents of your ```.bash_profile```.  Try checking them and/or restart your terminal.  It seems likely it's something related to how your settings it.

**Comment by sjmack** [comment]
Okay. I've got all the path issue straightened out and its working now! Thanks.

**Comment by alexlancaster** [comment]
Excellent, is there any updates to the docs we can make that would make things clearer?

**Comment by sjmack** [comment]
Just to make it clear that the PATH variable has to be set a specific way to make use of MacPort. I had to do the manual MacPath import, as the installer didn't work for me, so that may have been the source of my problems.

**Comment by alexlancaster** [comment]
Were the changes to ```.bash_login``` not sufficient? Feel free to suggest some wording changes if you have something specific in mind.

**Comment by alexlancaster** [comment]
Hmm, interesting that the installer had problems, what was the symptom?

**Comment by sjmack** [comment]
I've attached a screenshot of the failed installer below.  It is amazingly unhelpful. I interpreted the additional error message, in the upper right-hand corner of the window, which I couldn't completely read because I can't resize the installer window, to be suggesting that I install manually.

![macports-install_fail](https://user-images.githubusercontent.com/8935284/27005704-a0102214-4dd8-11e7-9b5f-4979bf1db893.png)
.

**Comment by sjmack** [comment]
Reorganizing the PATH variable in .bash_profile was sufficient, but users should be made aware that they may need to do that.

**Comment by alexlancaster** [comment]
Let me know if this seems sufficient (see updates) and I'll close.  Dunno what's happening on MacPorts.

**Comment by alexlancaster** [comment]
Closing (re-open if problem reoccurs).
