### ISSUE TITLE
Error creating html from .rst using Sphinx

### ISSUE THREAD

**Issue by mmariani123** [alexlancaster/pypop#98]
**Describe the bug**

I have installed a new miniconda environment in the home directory of the ubuntu app on windows 11 and installed sphinx. 
I then cloned my newest GitHub fork of Pypop. I moved in the new pypop/website directory but the sphinx build command throws an error

**To Reproduce**
1.) #create and activate a new python3 miniconda environment (ubuntu 22.04 on windows 11)
2.) pip install --user sphinx piccolo-theme sphinx_rtd_theme myst_parser rst2pdf sphinx_togglebutton
3.) git clone https://github.com/mmariani123/pypop.git
4.) cd pypop/website
5.) sphinx-build docs _build
6.). See error

**Expected behavior**
Sphinx will build the documentation and I can see view locally in my browser. 

**Screenshots**

<img width="563" alt="pypop_sphinx_error_07212023" src="https://github.com/alexlancaster/pypop/assets/37840656/f0834c82-916f-4162-a5fb-1371bd24215f">

**Desktop (please complete the following information):**
Ubuntu App 22.04 WSL2 on Windows 11

**Comment by alexlancaster** [comment]
> **Describe the bug**
> 
> I have installed a new miniconda environment in the home directory of the ubuntu app on windows 11 and installed sphinx. I then cloned my newest GitHub fork of Pypop. I moved in the new pypop/website directory but the sphinx build command throws an error
> 
> **To Reproduce** 1.) #create and activate a new python3 miniconda environment (ubuntu 22.04 on windows 11) 2.) pip install --user sphinx piccolo-theme sphinx_rtd_theme myst_parser rst2pdf sphinx_togglebutton 3.) git clone https://github.com/mmariani123/pypop.git 4.) cd pypop/website 5.) sphinx-build docs _build 6.). See error

Ah, good catch! I forgot to update the `website/README.md` after I renamed the directory from `docs` to `website` (to avoid confusion with the `docs` subdirectory inside `website`). This is fixed in #99

**Comment by alexlancaster** [comment]
Also note that I mention in this sectionhttps://github.com/alexlancaster/pypop/tree/main/website#major-modifications that the `documentation.yml` workflow file should be considered the ultimate reference, in case the docs get out of date.
